using System.Text;

namespace UnicodeCldr.LocaleData.Generator;

/// <summary>Summary of a unit-patterns generation run.</summary>
public sealed record UnitsGenerationResult(int EntryCount, string OutputPath);

/// <summary>
/// Emits the committed <c>CldrUnitData</c> source file: a map from
/// <c>"&lt;locale&gt;|&lt;unit&gt;|&lt;display&gt;|&lt;count&gt;"</c> to a unit pattern.
/// </summary>
public static class CldrUnitsCodeGenerator
{
    public static UnitsGenerationResult Generate(string dataDirectory, string cldrVersion, string outputPath)
    {
        var patterns = CldrUnitsParser.ParseAll(dataDirectory);
        if (patterns.Count == 0)
        {
            throw new InvalidOperationException($"No unit patterns were parsed from '{dataDirectory}'.");
        }

        var sb = new StringBuilder();
        sb.Append("// <auto-generated>\n");
        sb.Append("//   Generated by UnicodeCldr.LocaleData.Generator. Do not edit by hand.\n");
        sb.Append($"//   Source: CLDR {cldrVersion} unit patterns ({patterns.Count} entries).\n");
        sb.Append("//   Run `dotnet run --project src/UnicodeCldr.LocaleData.DataTool -- update <version>` to refresh.\n");
        sb.Append("// </auto-generated>\n");
        sb.Append("#nullable enable\n");
        sb.Append("using System.Collections.Generic;\n\n");
        sb.Append("namespace UnicodeCldr.LocaleData;\n\n");
        sb.Append("internal static class CldrUnitData\n{\n");
        sb.Append($"    public const string CldrVersion = \"{cldrVersion}\";\n\n");
        sb.Append("    // key: \"<locale>|<unit>|<display>|<count>\"; value: pattern with a {0} placeholder.\n");
        sb.Append("    public static readonly Dictionary<string, string> Patterns = new(StringComparer.Ordinal)\n    {\n");

        foreach (var pattern in patterns
            .OrderBy(static p => p.Locale, StringComparer.Ordinal)
            .ThenBy(static p => p.Unit, StringComparer.Ordinal)
            .ThenBy(static p => p.Display, StringComparer.Ordinal)
            .ThenBy(static p => p.Count, StringComparer.Ordinal))
        {
            sb.Append("        [\"");
            sb.Append(pattern.Locale);
            sb.Append('|');
            sb.Append(pattern.Unit);
            sb.Append('|');
            sb.Append(pattern.Display);
            sb.Append('|');
            sb.Append(pattern.Count);
            sb.Append("\"] = ");
            sb.Append(Quote(pattern.Pattern));
            sb.Append(",\n");
        }

        sb.Append("    };\n");
        sb.Append("}\n");

        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
        File.WriteAllText(outputPath, sb.ToString());

        return new UnitsGenerationResult(patterns.Count, outputPath);
    }

    private static string Quote(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');
        foreach (var ch in value)
        {
            switch (ch)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                default:
                    if (ch is >= ' ' and <= '~')
                    {
                        sb.Append(ch);
                    }
                    else
                    {
                        sb.Append("\\u");
                        sb.Append(((int)ch).ToString("x4"));
                    }
                    break;
            }
        }

        sb.Append('"');
        return sb.ToString();
    }
}
