using System.Text;

namespace UnicodeCldr.LocaleData.Generator;

/// <summary>Summary of a relative-time generation run.</summary>
public sealed record RelativeTimeGenerationResult(int PatternCount, int ExactCount, string OutputPath);

/// <summary>
/// Emits the committed <c>CldrRelativeTimeData</c> source file: a
/// <c>"&lt;locale&gt;|&lt;unit&gt;|&lt;style&gt;|&lt;tense&gt;|&lt;count&gt;"</c> → pattern map and a
/// <c>"&lt;locale&gt;|&lt;unit&gt;|&lt;style&gt;|&lt;offset&gt;"</c> → exact-phrase map, used to drive
/// <c>Intl.RelativeTimeFormat</c>.
/// </summary>
public static class CldrRelativeTimeCodeGenerator
{
    // The CLDR plural-category order, used so counts emit zero→other rather than
    // alphabetically.
    private static readonly string[] CountOrder = { "zero", "one", "two", "few", "many", "other" };

    private static readonly string[] StyleOrder = { "long", "short", "narrow" };
    private static readonly string[] TenseOrder = { "future", "past" };

    private static readonly Dictionary<string, int> UnitRank =
        CldrRelativeTimeParser.Units
            .Select(static (u, i) => (u, i))
            .ToDictionary(static t => t.u, static t => t.i, StringComparer.Ordinal);

    public static RelativeTimeGenerationResult Generate(string dataDirectory, string cldrVersion, string outputPath)
    {
        var data = CldrRelativeTimeParser.ParseAll(dataDirectory);
        if (data.Patterns.Count == 0)
        {
            throw new InvalidOperationException($"No relative-time patterns were parsed from '{dataDirectory}'.");
        }

        var sb = new StringBuilder();
        sb.Append("// <auto-generated>\n");
        sb.Append("//   Generated by UnicodeCldr.LocaleData.Generator. Do not edit by hand.\n");
        sb.Append($"//   Source: CLDR {cldrVersion} relative-time data ({data.Patterns.Count} patterns, {data.Exacts.Count} exact phrases).\n");
        sb.Append("//   Run `dotnet run --project src/UnicodeCldr.LocaleData.DataTool -- update <version>` to refresh.\n");
        sb.Append("// </auto-generated>\n");
        sb.Append("#nullable enable\n");
        sb.Append("using System.Collections.Generic;\n\n");
        sb.Append("namespace UnicodeCldr.LocaleData;\n\n");
        sb.Append("internal static class CldrRelativeTimeData\n{\n");
        sb.Append($"    public const string CldrVersion = \"{cldrVersion}\";\n\n");

        sb.Append("    // key: \"<locale>|<unit>|<style>|<tense>|<count>\"; value: relative-time pattern with a {0} placeholder.\n");
        sb.Append("    public static readonly Dictionary<string, string> Patterns = new(StringComparer.Ordinal)\n    {\n");
        foreach (var pattern in data.Patterns
            .OrderBy(static p => p.Locale, StringComparer.Ordinal)
            .ThenBy(static p => UnitRank[p.Unit])
            .ThenBy(static p => Array.IndexOf(StyleOrder, p.Style))
            .ThenBy(static p => Array.IndexOf(TenseOrder, p.Tense))
            .ThenBy(static p => Array.IndexOf(CountOrder, p.Count)))
        {
            sb.Append("        [\"");
            sb.Append(pattern.Locale);
            sb.Append('|');
            sb.Append(pattern.Unit);
            sb.Append('|');
            sb.Append(pattern.Style);
            sb.Append('|');
            sb.Append(pattern.Tense);
            sb.Append('|');
            sb.Append(pattern.Count);
            sb.Append("\"] = ");
            sb.Append(Quote(pattern.Pattern));
            sb.Append(",\n");
        }

        sb.Append("    };\n\n");

        sb.Append("    // key: \"<locale>|<unit>|<style>|<offset>\"; value: exact relative phrase (e.g. \"yesterday\").\n");
        sb.Append("    public static readonly Dictionary<string, string> Exact = new(StringComparer.Ordinal)\n    {\n");
        foreach (var exact in data.Exacts
            .OrderBy(static e => e.Locale, StringComparer.Ordinal)
            .ThenBy(static e => UnitRank[e.Unit])
            .ThenBy(static e => Array.IndexOf(StyleOrder, e.Style))
            .ThenBy(static e => e.Offset))
        {
            sb.Append("        [\"");
            sb.Append(exact.Locale);
            sb.Append('|');
            sb.Append(exact.Unit);
            sb.Append('|');
            sb.Append(exact.Style);
            sb.Append('|');
            sb.Append(exact.Offset);
            sb.Append("\"] = ");
            sb.Append(Quote(exact.Phrase));
            sb.Append(",\n");
        }

        sb.Append("    };\n");
        sb.Append("}\n");

        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
        File.WriteAllText(outputPath, sb.ToString());

        return new RelativeTimeGenerationResult(data.Patterns.Count, data.Exacts.Count, outputPath);
    }

    private static string Quote(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');
        foreach (var ch in value)
        {
            switch (ch)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                default:
                    if (ch is >= ' ' and <= '~')
                    {
                        sb.Append(ch);
                    }
                    else
                    {
                        sb.Append("\\u");
                        sb.Append(((int)ch).ToString("x4"));
                    }
                    break;
            }
        }

        sb.Append('"');
        return sb.ToString();
    }
}
