using System.Text;
using System.Text.Json;

namespace UnicodeCldr.LocaleData.Generator;

/// <summary>Summary of a time-zone-names generation run.</summary>
public sealed record TimeZoneNamesGenerationResult(int ZoneCount, int NameCount, string OutputPath);

/// <summary>
/// Emits the committed <c>CldrTimeZoneData</c> source file: the IANA-zone → metazone map
/// (from supplemental <c>metaZones.json</c>) and the localized metazone display names
/// (from each locale's <c>timeZoneNames.json</c>), used by <c>Intl.DateTimeFormat</c>'s
/// <c>timeZoneName</c> option for the non-offset styles (long / short / generic).
/// </summary>
public static class CldrTimeZoneNamesCodeGenerator
{
    private static readonly string[] Widths = { "long", "short" };
    private static readonly string[] Types = { "generic", "standard", "daylight" };

    public static TimeZoneNamesGenerationResult Generate(string dataDirectory, string supplementalDirectory, string cldrVersion, string outputPath)
    {
        var zoneToMetazone = ParseZoneToMetazone(Path.Combine(supplementalDirectory, "metaZones.json"));
        if (zoneToMetazone.Count == 0)
            throw new InvalidOperationException($"No zone→metazone mappings were parsed from '{supplementalDirectory}'.");

        // "<locale>|<metazone>|<width>|<type>" -> name. Only locales that ship a timeZoneNames.json
        // are emitted (currently English is curated; other locales fall back to the GMT offset).
        var names = new SortedDictionary<string, string>(StringComparer.Ordinal);
        foreach (var dir in Directory.EnumerateDirectories(dataDirectory).OrderBy(static d => d, StringComparer.Ordinal))
        {
            var file = Path.Combine(dir, "timeZoneNames.json");
            if (File.Exists(file))
                ParseMetazoneNames(file, Path.GetFileName(dir).ToLowerInvariant(), names);
        }
        if (names.Count == 0)
            throw new InvalidOperationException($"No metazone names were parsed from '{dataDirectory}'.");

        var sb = new StringBuilder();
        sb.Append("// <auto-generated>\n");
        sb.Append("//   Generated by UnicodeCldr.LocaleData.Generator. Do not edit by hand.\n");
        sb.Append($"//   Source: CLDR {cldrVersion} time-zone names ({zoneToMetazone.Count} zones, {names.Count} names).\n");
        sb.Append("//   Run `dotnet run --project src/UnicodeCldr.LocaleData.DataTool -- update <version>` to refresh.\n");
        sb.Append("// </auto-generated>\n");
        sb.Append("#nullable enable\n");
        sb.Append("using System.Collections.Generic;\n\n");
        sb.Append("namespace UnicodeCldr.LocaleData;\n\n");
        sb.Append("internal static class CldrTimeZoneData\n{\n");
        sb.Append($"    public const string CldrVersion = \"{cldrVersion}\";\n\n");

        // IANA zone -> most-recent metazone.
        sb.Append("    public static readonly Dictionary<string, string> ZoneToMetazone = new(StringComparer.Ordinal)\n    {\n");
        foreach (var (zone, mz) in zoneToMetazone.OrderBy(static p => p.Key, StringComparer.Ordinal))
            sb.Append($"        [{Quote(zone)}] = {Quote(mz)},\n");
        sb.Append("    };\n\n");

        // "<locale>|<metazone>|<width>|<type>" -> localized display name.
        sb.Append("    public static readonly Dictionary<string, string> MetazoneNames = new(StringComparer.Ordinal)\n    {\n");
        foreach (var (key, name) in names)
            sb.Append($"        [{Quote(key)}] = {Quote(name)},\n");
        sb.Append("    };\n");
        sb.Append("}\n");

        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
        File.WriteAllText(outputPath, sb.ToString());
        return new TimeZoneNamesGenerationResult(zoneToMetazone.Count, names.Count, outputPath);
    }

    // supplemental.metaZones.metazoneInfo.timezone is a tree (area → … → [usesMetazone]); the leaf
    // array lists the metazones a zone has used over time. The most recent (last) one is kept.
    private static Dictionary<string, string> ParseZoneToMetazone(string path)
    {
        var map = new Dictionary<string, string>(StringComparer.Ordinal);
        if (!File.Exists(path))
            return map;

        using var document = JsonDocument.Parse(File.ReadAllText(path));
        if (document.RootElement.TryGetProperty("supplemental", out var supplemental)
            && supplemental.TryGetProperty("metaZones", out var metaZones)
            && metaZones.TryGetProperty("metazoneInfo", out var info)
            && info.TryGetProperty("timezone", out var timezone))
        {
            WalkZones(timezone, "", map);
        }

        return map;
    }

    private static void WalkZones(JsonElement element, string path, Dictionary<string, string> map)
    {
        if (element.ValueKind == JsonValueKind.Array)
        {
            string? metazone = null;
            foreach (var entry in element.EnumerateArray())
                if (entry.TryGetProperty("usesMetazone", out var uses) && uses.TryGetProperty("_mzone", out var mz))
                    metazone = mz.GetString();
            if (metazone is not null)
                map[path] = metazone;
            return;
        }

        if (element.ValueKind == JsonValueKind.Object)
            foreach (var property in element.EnumerateObject())
                WalkZones(property.Value, path.Length == 0 ? property.Name : $"{path}/{property.Name}", map);
    }

    // main.<locale>.dates.timeZoneNames.metazone.<Metazone>.<width>.<type>
    private static void ParseMetazoneNames(string path, string locale, SortedDictionary<string, string> names)
    {
        using var document = JsonDocument.Parse(File.ReadAllText(path));
        if (!document.RootElement.TryGetProperty("main", out var main)
            || !main.TryGetProperty(locale, out var localeNode)
            || !localeNode.TryGetProperty("dates", out var dates)
            || !dates.TryGetProperty("timeZoneNames", out var tzn)
            || !tzn.TryGetProperty("metazone", out var metazones))
        {
            return;
        }

        foreach (var metazone in metazones.EnumerateObject())
        {
            foreach (var width in Widths)
            {
                if (!metazone.Value.TryGetProperty(width, out var widthNode))
                    continue;
                foreach (var type in Types)
                {
                    if (widthNode.TryGetProperty(type, out var value) && value.GetString() is { Length: > 0 } name)
                        names[$"{locale}|{metazone.Name}|{width}|{type}"] = name;
                }
            }
        }
    }

    private static string Quote(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');
        foreach (var ch in value)
        {
            switch (ch)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                default:
                    if (ch is >= ' ' and <= '~') sb.Append(ch);
                    else { sb.Append("\\u"); sb.Append(((int)ch).ToString("x4")); }
                    break;
            }
        }

        sb.Append('"');
        return sb.ToString();
    }
}
