using System.Text;

namespace UnicodeCldr.LocaleData.Generator;

/// <summary>Summary of a date-data generation run.</summary>
public sealed record DatesGenerationResult(int NameCount, int RuleCount, string OutputPath);

/// <summary>
/// Emits the committed <c>CldrDateData</c> source file: day-period names keyed by
/// <c>"&lt;locale&gt;|&lt;period&gt;|&lt;width&gt;"</c> and the day-period rules per locale.
/// </summary>
public static class CldrDatesCodeGenerator
{
    public static DatesGenerationResult Generate(string dataDirectory, string supplementalDirectory, string cldrVersion, string outputPath)
    {
        var model = CldrDatesParser.ParseAll(dataDirectory, supplementalDirectory);
        if (model.Names.Count == 0)
        {
            throw new InvalidOperationException($"No day-period names were parsed from '{dataDirectory}'.");
        }

        var sb = new StringBuilder();
        sb.Append("// <auto-generated>\n");
        sb.Append("//   Generated by UnicodeCldr.LocaleData.Generator. Do not edit by hand.\n");
        sb.Append($"//   Source: CLDR {cldrVersion} day periods ({model.Names.Count} names, {model.Rules.Count} rule sets).\n");
        sb.Append("//   Run `dotnet run --project src/UnicodeCldr.LocaleData.DataTool -- update <version>` to refresh.\n");
        sb.Append("// </auto-generated>\n");
        sb.Append("#nullable enable\n");
        sb.Append("using System.Collections.Generic;\n\n");
        sb.Append("namespace UnicodeCldr.LocaleData;\n\n");
        sb.Append("internal static class CldrDateData\n{\n");
        sb.Append($"    public const string CldrVersion = \"{cldrVersion}\";\n\n");

        // Day-period names: "<locale>|<period>|<width>" -> name.
        sb.Append("    public static readonly Dictionary<string, string> DayPeriodNames = new(StringComparer.Ordinal)\n    {\n");
        foreach (var name in model.Names
            .OrderBy(static n => n.Locale, StringComparer.Ordinal)
            .ThenBy(static n => n.Period, StringComparer.Ordinal)
            .ThenBy(static n => n.Width, StringComparer.Ordinal))
        {
            sb.Append("        [\"");
            sb.Append(name.Locale);
            sb.Append('|');
            sb.Append(name.Period);
            sb.Append('|');
            sb.Append(name.Width);
            sb.Append("\"] = ");
            sb.Append(Quote(name.Name));
            sb.Append(",\n");
        }

        sb.Append("    };\n\n");

        // Day-period rules: "<locale>" -> rule string.
        sb.Append("    public static readonly Dictionary<string, string> DayPeriodRules = new(StringComparer.Ordinal)\n    {\n");
        foreach (var rule in model.Rules.OrderBy(static r => r.Locale, StringComparer.Ordinal))
        {
            sb.Append("        [\"");
            sb.Append(rule.Locale);
            sb.Append("\"] = ");
            sb.Append(Quote(rule.Rules));
            sb.Append(",\n");
        }

        sb.Append("    };\n");
        sb.Append("}\n");

        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
        File.WriteAllText(outputPath, sb.ToString());

        return new DatesGenerationResult(model.Names.Count, model.Rules.Count, outputPath);
    }

    private static string Quote(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');
        foreach (var ch in value)
        {
            switch (ch)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                default:
                    if (ch is >= ' ' and <= '~')
                    {
                        sb.Append(ch);
                    }
                    else
                    {
                        sb.Append("\\u");
                        sb.Append(((int)ch).ToString("x4"));
                    }
                    break;
            }
        }

        sb.Append('"');
        return sb.ToString();
    }
}
