using System.Text;

namespace UnicodeCldr.LocaleData.Generator;

/// <summary>Summary of a currency-data generation run.</summary>
public sealed record CurrencyGenerationResult(int LayoutCount, int SymbolCount, int DigitsCount, string OutputPath);

/// <summary>
/// Emits the committed <c>CldrCurrencyData</c> source file: per-locale layout, the
/// curated per-(locale,currency) symbols, and the non-default fraction digits.
/// </summary>
public static class CldrCurrencyCodeGenerator
{
    public static CurrencyGenerationResult Generate(string dataDirectory, string supplementalDirectory, string cldrVersion, string outputPath)
    {
        var model = CldrCurrencyParser.ParseAll(dataDirectory, supplementalDirectory);
        if (model.Layouts.Count == 0)
        {
            throw new InvalidOperationException($"No currency layouts were parsed from '{dataDirectory}'.");
        }

        var sb = new StringBuilder();
        sb.Append("// <auto-generated>\n");
        sb.Append("//   Generated by UnicodeCldr.LocaleData.Generator. Do not edit by hand.\n");
        sb.Append($"//   Source: CLDR {cldrVersion} currency data ({model.Layouts.Count} locales, {model.Symbols.Count} symbols).\n");
        sb.Append("//   Run `dotnet run --project src/UnicodeCldr.LocaleData.DataTool -- update <version>` to refresh.\n");
        sb.Append("// </auto-generated>\n");
        sb.Append("#nullable enable\n");
        sb.Append("using System.Collections.Generic;\n\n");
        sb.Append("namespace UnicodeCldr.LocaleData;\n\n");
        sb.Append("internal static class CldrCurrencyData\n{\n");
        sb.Append($"    public const string CldrVersion = \"{cldrVersion}\";\n\n");

        // Layout: "<locale>" -> [symbolAfter("0"/"1"), spacing, accountingParens("0"/"1")].
        sb.Append("    public static readonly Dictionary<string, string[]> Layout = new(StringComparer.Ordinal)\n    {\n");
        foreach (var layout in model.Layouts.OrderBy(static l => l.Locale, StringComparer.Ordinal))
        {
            sb.Append("        [\"");
            sb.Append(layout.Locale);
            sb.Append("\"] = new[] { ");
            sb.Append(layout.SymbolAfter ? "\"1\"" : "\"0\"");
            sb.Append(", ");
            sb.Append(Quote(layout.Spacing));
            sb.Append(", ");
            sb.Append(layout.AccountingParens ? "\"1\"" : "\"0\"");
            sb.Append(" },\n");
        }

        sb.Append("    };\n\n");

        // Symbols: "<locale>|<CODE>|<variant>" -> symbol (variant: symbol | narrow).
        sb.Append("    public static readonly Dictionary<string, string> Symbols = new(StringComparer.Ordinal)\n    {\n");
        foreach (var symbol in model.Symbols
            .OrderBy(static s => s.Locale, StringComparer.Ordinal)
            .ThenBy(static s => s.Code, StringComparer.Ordinal))
        {
            sb.Append("        [\"");
            sb.Append(symbol.Locale);
            sb.Append('|');
            sb.Append(symbol.Code);
            sb.Append("|symbol\"] = ");
            sb.Append(Quote(symbol.Symbol));
            sb.Append(",\n");
            if (symbol.NarrowSymbol != symbol.Symbol)
            {
                sb.Append("        [\"");
                sb.Append(symbol.Locale);
                sb.Append('|');
                sb.Append(symbol.Code);
                sb.Append("|narrow\"] = ");
                sb.Append(Quote(symbol.NarrowSymbol));
                sb.Append(",\n");
            }
        }

        sb.Append("    };\n\n");

        // Digits: "<CODE>" -> fraction digits (only currencies that differ from 2).
        sb.Append("    public static readonly Dictionary<string, int> Digits = new(StringComparer.Ordinal)\n    {\n");
        foreach (var digits in model.Digits.OrderBy(static d => d.Code, StringComparer.Ordinal))
        {
            sb.Append("        [\"");
            sb.Append(digits.Code);
            sb.Append("\"] = ");
            sb.Append(digits.Digits);
            sb.Append(",\n");
        }

        sb.Append("    };\n");
        sb.Append("}\n");

        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
        File.WriteAllText(outputPath, sb.ToString());

        return new CurrencyGenerationResult(model.Layouts.Count, model.Symbols.Count, model.Digits.Count, outputPath);
    }

    private static string Quote(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');
        foreach (var ch in value)
        {
            switch (ch)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                default:
                    if (ch is >= ' ' and <= '~')
                    {
                        sb.Append(ch);
                    }
                    else
                    {
                        sb.Append("\\u");
                        sb.Append(((int)ch).ToString("x4"));
                    }
                    break;
            }
        }

        sb.Append('"');
        return sb.ToString();
    }
}
