using System.Text;

namespace UnicodeCldr.LocaleData.Generator;

/// <summary>Summary of a plural-rules generation run.</summary>
/// <param name="EntryCount">The number of (locale, type) entries encoded.</param>
/// <param name="OutputPath">The path of the generated source file.</param>
public sealed record PluralGenerationResult(int EntryCount, string OutputPath);

/// <summary>
/// Parses CLDR plural data and emits the committed <c>CldrPluralData</c> source file
/// (a flat <c>[category, condition, ...]</c> array per <c>"&lt;locale&gt;|&lt;type&gt;"</c>).
/// </summary>
public static class CldrPluralCodeGenerator
{
    /// <summary>Runs the full parse → emit pipeline.</summary>
    public static PluralGenerationResult Generate(string supplementalDirectory, string cldrVersion, string outputPath)
    {
        var locales = CldrPluralRulesParser.ParseAll(supplementalDirectory);
        if (locales.Count == 0)
        {
            throw new InvalidOperationException($"No plural rules were parsed from '{supplementalDirectory}'.");
        }

        var sb = new StringBuilder();
        sb.Append("// <auto-generated>\n");
        sb.Append("//   Generated by UnicodeCldr.LocaleData.Generator. Do not edit by hand.\n");
        sb.Append($"//   Source: CLDR {cldrVersion} plural rules ({locales.Count} (locale, type) entries).\n");
        sb.Append("//   Run `dotnet run --project src/UnicodeCldr.LocaleData.DataTool -- update <version>` to refresh.\n");
        sb.Append("// </auto-generated>\n");
        sb.Append("#nullable enable\n");
        sb.Append("using System.Collections.Generic;\n\n");
        sb.Append("namespace UnicodeCldr.LocaleData;\n\n");
        sb.Append("internal static class CldrPluralData\n{\n");
        sb.Append($"    public const string CldrVersion = \"{cldrVersion}\";\n\n");
        sb.Append("    // key: \"<locale>|<type>\"; value: flat [category, condition, ...] for the\n");
        sb.Append("    // non-\"other\" categories in CLDR order (\"other\" is the implicit fallback).\n");
        sb.Append("    public static readonly Dictionary<string, string[]> Rules = new(StringComparer.Ordinal)\n");
        sb.Append("    {\n");

        foreach (var entry in locales
            .OrderBy(static l => l.Locale, StringComparer.Ordinal)
            .ThenBy(static l => l.Type, StringComparer.Ordinal))
        {
            sb.Append("        [\"");
            sb.Append(entry.Locale);
            sb.Append('|');
            sb.Append(entry.Type);
            sb.Append("\"] = new[] { ");
            for (var i = 0; i < entry.Rules.Count; i++)
            {
                if (i > 0)
                {
                    sb.Append(", ");
                }

                sb.Append(Quote(entry.Rules[i].Category));
                sb.Append(", ");
                sb.Append(Quote(entry.Rules[i].Condition));
            }

            sb.Append(" },\n");
        }

        sb.Append("    };\n");
        sb.Append("}\n");

        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
        File.WriteAllText(outputPath, sb.ToString());

        return new PluralGenerationResult(locales.Count, outputPath);
    }

    private static string Quote(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');
        foreach (var ch in value)
        {
            switch (ch)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                default:
                    if (ch is >= ' ' and <= '~')
                    {
                        sb.Append(ch);
                    }
                    else
                    {
                        sb.Append("\\u");
                        sb.Append(((int)ch).ToString("x4"));
                    }
                    break;
            }
        }

        sb.Append('"');
        return sb.ToString();
    }
}
