using System.Text;

namespace UnicodeCldr.LocaleData.Generator;

/// <summary>Summary of a list-patterns generation run.</summary>
/// <param name="LocaleCount">The number of locales encoded.</param>
/// <param name="EntryCount">The number of (locale, type, style) entries encoded.</param>
/// <param name="OutputPath">The path of the generated source file.</param>
public sealed record ListGenerationResult(int LocaleCount, int EntryCount, string OutputPath);

/// <summary>
/// Parses CLDR list-pattern data and emits the committed <c>CldrListData</c> source
/// file consumed by the runtime library.
/// </summary>
public static class CldrListCodeGenerator
{
    // Stable emit order so regenerated files have minimal diffs.
    private static readonly string[] TypeOrder = { "conjunction", "disjunction", "unit" };
    private static readonly string[] StyleOrder = { "long", "short", "narrow" };

    /// <summary>Runs the full parse → emit pipeline.</summary>
    public static ListGenerationResult Generate(string dataDirectory, string cldrVersion, string outputPath)
    {
        var locales = CldrListPatternsParser.ParseAll(dataDirectory);
        if (locales.Count == 0)
        {
            throw new InvalidOperationException($"No listPatterns.json files were parsed from '{dataDirectory}'.");
        }

        var entryCount = 0;
        var sb = new StringBuilder();
        sb.Append("// <auto-generated>\n");
        sb.Append("//   Generated by UnicodeCldr.LocaleData.Generator. Do not edit by hand.\n");
        sb.Append($"//   Source: CLDR {cldrVersion} list patterns ({locales.Count} locales).\n");
        sb.Append("//   Run `dotnet run --project src/UnicodeCldr.LocaleData.DataTool -- update <version>` to refresh.\n");
        sb.Append("// </auto-generated>\n");
        sb.Append("#nullable enable\n");
        sb.Append("using System.Collections.Generic;\n\n");
        sb.Append("namespace UnicodeCldr.LocaleData;\n\n");
        sb.Append("internal static class CldrListData\n{\n");
        sb.Append($"    public const string CldrVersion = \"{cldrVersion}\";\n\n");
        sb.Append("    // key: \"<language>|<type>|<style>\"; value: [start, middle, end, pair]\n");
        sb.Append("    public static readonly Dictionary<string, string[]> Patterns = new(StringComparer.Ordinal)\n");
        sb.Append("    {\n");

        foreach (var locale in locales.OrderBy(static l => l.Language, StringComparer.Ordinal))
        {
            foreach (var type in TypeOrder)
            {
                foreach (var style in StyleOrder)
                {
                    if (!locale.ByTypeStyle.TryGetValue($"{type}|{style}", out var p))
                    {
                        continue;
                    }

                    sb.Append("        [\"");
                    sb.Append(locale.Language);
                    sb.Append('|');
                    sb.Append(type);
                    sb.Append('|');
                    sb.Append(style);
                    sb.Append("\"] = new[] { ");
                    sb.Append(Quote(p.Start));
                    sb.Append(", ");
                    sb.Append(Quote(p.Middle));
                    sb.Append(", ");
                    sb.Append(Quote(p.End));
                    sb.Append(", ");
                    sb.Append(Quote(p.Pair));
                    sb.Append(" },\n");
                    entryCount++;
                }
            }
        }

        sb.Append("    };\n");
        sb.Append("}\n");

        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
        File.WriteAllText(outputPath, sb.ToString());

        return new ListGenerationResult(locales.Count, entryCount, outputPath);
    }

    // Emits a C# string literal, escaping every non-printable-ASCII character as
    // \uXXXX so the generated source stays pure ASCII (diff-friendly, encoding-safe).
    private static string Quote(string value)
    {
        var sb = new StringBuilder(value.Length + 2);
        sb.Append('"');
        foreach (var ch in value)
        {
            switch (ch)
            {
                case '"': sb.Append("\\\""); break;
                case '\\': sb.Append("\\\\"); break;
                default:
                    if (ch is >= ' ' and <= '~')
                    {
                        sb.Append(ch);
                    }
                    else
                    {
                        sb.Append("\\u");
                        sb.Append(((int)ch).ToString("x4"));
                    }
                    break;
            }
        }

        sb.Append('"');
        return sb.ToString();
    }
}
