using System.Globalization;
using System.Text;

namespace UnicodeEmoji.StringProperties.Generator;

/// <summary>
/// Emits the generated <c>EmojiTrieData</c> C# source file from a <see cref="FlatTrie"/>.
/// </summary>
/// <remarks>
/// The output is deterministic and diff-friendly: arrays are wrapped at a fixed number of items per
/// line and code point keys are formatted as upper-case hex so a regenerated table produces a minimal,
/// reviewable diff.
/// </remarks>
public static class EmojiTrieSourceWriter
{
    private const int ItemsPerLine = 12;

    /// <summary>Produces the full text of the generated source file.</summary>
    /// <param name="trie">The flattened trie to emit.</param>
    /// <param name="unicodeEmojiVersion">The Unicode emoji version the data came from.</param>
    /// <param name="sequenceCount">The number of distinct input sequences (for the header summary).</param>
    /// <param name="maxSequenceLength">The longest sequence length in scalar values.</param>
    /// <returns>The generated C# source.</returns>
    public static string Write(FlatTrie trie, string unicodeEmojiVersion, int sequenceCount, int maxSequenceLength)
    {
        var sb = new StringBuilder(trie.EdgeCount * 8);

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//   Generated by UnicodeEmoji.StringProperties.Generator. Do not edit by hand.");
        sb.AppendLine($"//   Source: Unicode emoji {unicodeEmojiVersion} (emoji-sequences.txt, emoji-zwj-sequences.txt).");
        sb.AppendLine($"//   Sequences: {sequenceCount}, Nodes: {trie.NodeCount}, Edges: {trie.EdgeCount}.");
        sb.AppendLine("//   Run `dotnet run --project src/UnicodeEmoji.StringProperties.DataTool -- generate <version>` to refresh.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace UnicodeEmoji.StringProperties.Internal;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Generated, flattened emoji trie tables. See <see cref=\"EmojiTrie\"/> for the layout.</summary>");
        sb.AppendLine("internal static class EmojiTrieData");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>The Unicode emoji data version these tables were generated from.</summary>");
        sb.AppendLine($"    public const string UnicodeEmojiVersion = \"{unicodeEmojiVersion}\";");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>The number of distinct emoji sequences encoded in the trie.</summary>");
        sb.AppendLine($"    public const int SequenceCount = {sequenceCount};");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>The longest emoji sequence length, in Unicode scalar values.</summary>");
        sb.AppendLine($"    public const int MaxSequenceLength = {maxSequenceLength};");
        sb.AppendLine();

        AppendIntArray(sb, "ChildOffsets", "Per-node start offset into the edge arrays; length is node count + 1.", trie.ChildOffsets, hex: false);
        AppendIntArray(sb, "ChildKeys", "Edge scalar keys, sorted ascending within each node.", trie.ChildKeys, hex: true);
        AppendIntArray(sb, "ChildNodes", "Edge target node indices, parallel to ChildKeys.", trie.ChildNodes, hex: false);
        AppendByteArray(sb, "Props", "Per-node EmojiSequenceProperties flags; the node is terminal when non-zero.", trie.Props);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendIntArray(StringBuilder sb, string name, string summary, int[] values, bool hex)
    {
        sb.AppendLine($"    /// <summary>{summary}</summary>");
        sb.AppendLine($"    public static readonly int[] {name} =");
        sb.AppendLine("    {");
        AppendItems(sb, values.Length, i => hex ? ToHex(values[i]) : values[i].ToString(CultureInfo.InvariantCulture));
        sb.AppendLine("    };");
        sb.AppendLine();
    }

    private static void AppendByteArray(StringBuilder sb, string name, string summary, byte[] values)
    {
        sb.AppendLine($"    /// <summary>{summary}</summary>");
        sb.AppendLine($"    public static readonly byte[] {name} =");
        sb.AppendLine("    {");
        AppendItems(sb, values.Length, i => values[i].ToString(CultureInfo.InvariantCulture));
        sb.AppendLine("    };");
    }

    private static void AppendItems(StringBuilder sb, int count, Func<int, string> format)
    {
        for (int i = 0; i < count; i += ItemsPerLine)
        {
            sb.Append("        ");
            int end = Math.Min(i + ItemsPerLine, count);
            for (int j = i; j < end; j++)
            {
                sb.Append(format(j));
                sb.Append(',');
                if (j + 1 < end)
                {
                    sb.Append(' ');
                }
            }

            sb.AppendLine();
        }
    }

    private static string ToHex(int value) => "0x" + value.ToString("X", CultureInfo.InvariantCulture);
}
