#!/usr/bin/env python3
# Generates Script and Script_Extensions range tables (Unicode 17.0.0) as C# for
# the Broiler.Unicode UnicodeProperties library.
import sys

MAXCP = 0x110000

def parse_ranges(path):
    """Yields (lo, hi, value) from a UCD list file."""
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            parts = [p.strip() for p in line.split(";")]
            if len(parts) < 2:
                continue
            cps = parts[0]
            if ".." in cps:
                lo, hi = (int(x, 16) for x in cps.split(".."))
            else:
                lo = hi = int(cps, 16)
            yield lo, hi, parts[1]

def script_aliases(path):
    """Returns {long_name: [short, long, ...aliases]} for the 'sc' property."""
    out = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line.startswith("sc ;"):
                continue
            parts = [p.strip() for p in line.split(";")]
            # sc ; Short ; Long ; (extra aliases)
            names = parts[1:]
            short, long_ = names[0], names[1]
            out[long_] = list(dict.fromkeys(names))  # dedupe, keep order
    return out

def normalize_ranges_from_cps(cps_sorted):
    merged = []
    for cp in cps_sorted:
        if merged and cp <= merged[-1][1] + 1:
            merged[-1] = (merged[-1][0], cp)
        else:
            merged.append((cp, cp))
    return merged

def ranges_to_str(ranges):
    return ",".join(f"{lo:X}" if lo == hi else f"{lo:X}-{hi:X}" for lo, hi in ranges)

def norm_key(s):
    return s.replace("_", "").replace(" ", "").replace("-", "").lower()

def main():
    aliases = script_aliases("PropertyValueAliases.txt")
    long_by_short = {names[0]: long_ for long_, names in aliases.items()}

    # script_of[cp] = long script name (default "Unknown")
    script_of = ["Unknown"] * MAXCP
    for lo, hi, val in parse_ranges("Scripts.txt"):
        for cp in range(lo, hi + 1):
            script_of[cp] = val

    # explicit script extensions: cp -> [long names]
    scx_explicit = {}
    for lo, hi, val in parse_ranges("ScriptExtensions.txt"):
        longs = [long_by_short.get(code, code) for code in val.split()]
        for cp in range(lo, hi + 1):
            scx_explicit[cp] = longs

    # Bucket cps by Script and by Script_Extensions.
    script_buckets = {}
    scx_buckets = {}
    for cp in range(MAXCP):
        sc = script_of[cp]
        script_buckets.setdefault(sc, []).append(cp)
        for s in scx_explicit.get(cp, (sc,)):
            scx_buckets.setdefault(s, []).append(cp)

    def emit(buckets, classname, varname):
        entries = {}
        for long_, cps in buckets.items():
            ranges = normalize_ranges_from_cps(cps)
            enc = ranges_to_str(ranges)
            names = aliases.get(long_, [long_])
            for n in names:
                entries[norm_key(n)] = enc
        lines = [
            "// <auto-generated>",
            "//   Generated from the Unicode Character Database 17.0.0 by genscripts.py.",
            "//   Do not edit by hand.",
            "// </auto-generated>",
            "using System.Collections.Generic;",
            "",
            "namespace Broiler.Unicode.Properties;",
            "",
            f"internal static class {classname}",
            "{",
            f"    internal static readonly Dictionary<string, string> {varname} = new()",
            "    {",
        ]
        for k in sorted(entries):
            lines.append(f'        ["{k}"] = "{entries[k]}",')
        lines += ["    };", "}"]
        with open(f"{classname}.g.cs", "w", encoding="utf-8") as f:
            f.write("\n".join(lines) + "\n")
        print(f"{classname}: {len(entries)} keys, {len(buckets)} scripts")

    emit(script_buckets, "ScriptData", "Ranges")
    emit(scx_buckets, "ScriptExtensionsData", "Ranges")

main()
