#!/usr/bin/env python3
# Generates General_Category range tables (Unicode 17.0.0) as C# for the
# Broiler.Unicode UnicodeProperties library.
MAXCP = 0x110000

GROUPS = {
    "LC": ["Lu", "Ll", "Lt"],
    "L": ["Lu", "Ll", "Lt", "Lm", "Lo"],
    "M": ["Mn", "Mc", "Me"],
    "N": ["Nd", "Nl", "No"],
    "P": ["Pc", "Pd", "Ps", "Pe", "Pi", "Pf", "Po"],
    "S": ["Sm", "Sc", "Sk", "So"],
    "Z": ["Zs", "Zl", "Zp"],
    "C": ["Cc", "Cf", "Cs", "Co", "Cn"],
}

def gc_aliases(path):
    """Returns {canonical2: [all names]} for the 'gc' property."""
    out = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line.startswith("gc ;"):
                continue
            parts = [p.strip() for p in line.split(";")]
            names = parts[1:]
            out[names[0]] = list(dict.fromkeys(names))
    return out

def parse_gc(path):
    """gc_of[cp] = 2-letter category (default 'Cn')."""
    gc_of = ["Cn"] * MAXCP
    rows = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line:
                continue
            fields = line.split(";")
            rows.append((int(fields[0], 16), fields[1], fields[2]))
    i = 0
    while i < len(rows):
        cp, name, gc = rows[i]
        if name.endswith(", First>"):
            cp2 = rows[i + 1][0]
            for c in range(cp, cp2 + 1):
                gc_of[c] = gc
            i += 2
        else:
            gc_of[cp] = gc
            i += 1
    return gc_of

def normalize_ranges_from_cps(cps_sorted):
    merged = []
    for cp in cps_sorted:
        if merged and cp <= merged[-1][1] + 1:
            merged[-1] = (merged[-1][0], cp)
        else:
            merged.append((cp, cp))
    return merged

def ranges_to_str(ranges):
    return ",".join(f"{lo:X}" if lo == hi else f"{lo:X}-{hi:X}" for lo, hi in ranges)

def norm_key(s):
    return s.replace("_", "").replace(" ", "").replace("-", "").lower()

def main():
    aliases = gc_aliases("PropertyValueAliases.txt")
    gc_of = parse_gc("UnicodeData.txt")

    specific = {}  # gc2 -> [cps]
    for cp in range(MAXCP):
        specific.setdefault(gc_of[cp], []).append(cp)

    data = {}  # canonical -> ranges
    for gc2, cps in specific.items():
        data[gc2] = normalize_ranges_from_cps(cps)
    for grp, members in GROUPS.items():
        cps = []
        for m in members:
            cps.extend(specific.get(m, []))
        data[grp] = normalize_ranges_from_cps(sorted(cps))

    entries = {}
    for canon, ranges in data.items():
        enc = ranges_to_str(ranges)
        names = aliases.get(canon, [canon])
        for n in names:
            entries[norm_key(n)] = enc

    lines = [
        "// <auto-generated>",
        "//   Generated from the Unicode Character Database 17.0.0 by gengc.py.",
        "//   Do not edit by hand. Maps an ECMAScript-normalized General_Category value",
        "//   (canonical, long name, or alias) to its code-point ranges.",
        "// </auto-generated>",
        "using System.Collections.Generic;",
        "",
        "namespace Broiler.Unicode.Properties;",
        "",
        "internal static class GeneralCategoryData",
        "{",
        "    internal static readonly Dictionary<string, string> Ranges = new()",
        "    {",
    ]
    for k in sorted(entries):
        lines.append(f'        ["{k}"] = "{entries[k]}",')
    lines += ["    };", "}"]
    with open("GeneralCategoryData.g.cs", "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"GeneralCategoryData: {len(entries)} keys, {len(data)} categories")

main()
